### ISSUE TITLE
Nitor recipe turned off?

### ISSUE THREAD

**Issue by bruisedhound** [Haggle1996/RevolutionPack#116]
Hi there, I'm working my way through thaumcraft and noticed that I am unable to create nitor. I put the glowstone dust into my automatic crucible and the recipe doesn't come up at all. I've also tried in a regular crucible and same thing. I can't make any golem cores without nitor, along with a lot of other items. Is there a reason the recipe is turned off?

Thanks in advance.

**Comment by Haggle1996** [comment]
The recipe is definitely not turned off. Are you sure you got the research? I've made that mistake before -- done TC so many times I've forgotten which instance I had researched what on. :P

**Comment by bruisedhound** [comment]
Yes, I have almost my entire book researched by now.  My friend that I am playing this pack with is also unable to create it.

**Comment by Haggle1996** [comment]
Verified in SMP and SSP that I can craft Nitor without issue. In a heated crucible with water, I dropped three torches, three coal, and a glowstone dust. I received one Nitor.

**Comment by bruisedhound** [comment]
I just did the exact thing you said you did and all I got was a huge cloud of flux for my trouble.

**Comment by bruisedhound** [comment]
![nitor](https://cloud.githubusercontent.com/assets/15640658/10945443/732bbb82-82eb-11e5-9a35-8affa3fe3f48.png)
![nitor2](https://cloud.githubusercontent.com/assets/15640658/10945442/732856d6-82eb-11e5-9529-f2057f90f839.png)


Here are screenshots to prove I have the recipe.

**Comment by Haggle1996** [comment]
While I appreciate your frustration, the issue is not with the pack. The recipe is not disabled by me, and I've verified in two separate installations that it works fine in the current version of the pack (1.2.2.0).

At this point, you should be looking at your own installation. Are you running any non-standard mods? Have you disabled any features or permissions at the server level, perhaps with ForgeEssentials? Have you changed any config settings?

You may want to try installing a new instance of Revolution and trying again. I would first verify in SSP that it works for you. This would help narrow it down to a client or server issue.
