### ISSUE TITLE
Harder Ore's  RoC Compatability

### ISSUE THREAD

**Issue by Rokmonkey** [Haggle1996/RevolutionPack#128]
Any silk-touched 'Harder Ores' cannot be processed in RoC machines.  They all must be mined into chunks, compacted then processed in the machines.  They are ore dictionaried as oreXXXHard, perhaps it would be possible to minetweaker this in so that bedrock picks and silktouch enchanted boring machines can be used normally.

**Comment by Haggle1996** [comment]
http://reasonable-realism.wikia.com/wiki/Integration#Various_Ore_Mods

This is fixable if the RR author will add ore dictionary tags.

**Comment by Haggle1996** [comment]
I've fixed this in an alternate way. Instead of hoping for someone to fix something, I've made it so that Raw Ores can be processed in different machines at different rates. In addition to the sifter and packager, you can also process them on the alloy smelter, blast furnace, and arc furnace, at improving rates of return. For example, on the blast furnace, you get a 3:1 rate of raw ore:ore. Placing this ore in the RotaryCraft grinder will net you a 1:3 ratio of flakes, or a 1:1 ratio of raw ore:iron ingot, when fully processed. The ratio is even better with an extractor. This significantly reduces the usefulness of the silk touch enchant (it's still useful for some things), while simultaneously making tech progression much more useful, as you go from 7-8 ingots per stack of raw ore at the start, to nearly 100 ingots per stack in the mid-game.
