### ISSUE TITLE
Electrical age mod suggestion

### ISSUE THREAD

**Issue by Jezithyr** [Haggle1996/RevolutionPack#189]
I think electrical age might be a mod worth looking into for this pack. It has a hardcore tech-mod feel that is similar to Rotarycraft, but more based in electronics. https://electrical-age.net/ Electrical age is based off of a realistic electrical simulation system that models resistance, amperage, voltage, and power. The system is grounded in reality and requires at least a basic understanding of electrical principles such as ohms law. Its for these reasons that I think it would be a good addition to this pack. It may have some issues with malisis doors from what I've heard although these may be small in nature.

**Comment by Aivech** [comment]
It most likely will not be added to Revolution|1, but it could possibly be added to Revolution|2.
The final decision is up to @Haggle1996, however.

**Comment by Haggle1996** [comment]
Electrical Age used to be in REVOLUTION|1. It was removed primarily because no one used it, and it just added to pack bloat. No one used it primarily because it has a very high learning curve, blew up regularly (like creeper explosion, not crash), and overlapped with virtually every other mid-game mod.

IMHO, EA goes a couple of steps past the too-hard/enjoyable line, so it will not be added to either pack in it's current form. If the author significantly changes the mod in the future (I do keep an eye on it), I may revisit the decision.
