### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by GoaDi** [Haggle1996/RevolutionPack#195]
Please help, i have no idea what to do,

http://pastebin.com/pYmuk414

**Comment by Haggle1996** [comment]
It's complaining that you have a duplicate mod in the mods folder. Typically, this caused by two versions of the same mod in the same folder. Try reinstalling the pack and running it first without ShadersMod or any other mods you've added, then add back the extra mods once you've confirmed it's loading. Unfortunately, this log doesn't name the mod, I'd need to see the fml-client-latest.log in your /logs folder.

**Comment by imkSushi** [comment]
Actually, I had a crash the first time on startup, but it hasn't happened again. It is probably to do with some startup stuff that makes it crash when iit is deleted, but only needs to once.

**Comment by GoaDi** [comment]
Here are the logs 
http://pastebin.com/dE0MivGH

**Comment by Haggle1996** [comment]
Wow...there's just nothing useful in that log. Have you tried restarting your computer?

**Comment by GoaDi** [comment]
Yes, first thing i tried, is there any way i could re install the pack and keep my world/items?

**Comment by Aivech** [comment]
Make a copy of the save file.

**Comment by Haggle1996** [comment]
If you do a Reinstall from the AT Launcher, it won't delete your save files.

**Comment by GoaDi** [comment]
I Reinstalled it and its fine now :) thanks guys
