### ISSUE TITLE
Blaze Powder NEI crash

### ISSUE THREAD

**Issue by soleplayingames** [Haggle1996/RevolutionPack#205]
Well, two times I clicked on blaze powder in NEI, the game go boom bam, pssss. Cra&*h.

http://pastebin.com/hzuk3min

**Comment by Haggle1996** [comment]
Out of question, what happens if you update your Java version?

**Comment by RequiemStar** [comment]
This also happened to me today when I was trying to see how blase powder is crafted in the NEI. 
[crash-2016-02-05_17.14.14-client.txt](https://github.com/Haggle1996/RevolutionPack/files/120069/crash-2016-02-05_17.14.14-client.txt)

**Comment by DemonSeedxp** [comment]
I've just experienced this as well, my java is latest the version. I opened nei to see how to create the power because shapeless is disabled, so I left clicked and then crash. here's a [copy of the report](https://dl.dropboxusercontent.com/u/841137/Minecraft%20Crash%20Reports/crash-2016-02-05_19.52.27-client.txt)

**Comment by Haggle1996** [comment]
ReikaKalseki/Reika_Mods_Issues#488

We're waiting on what I presume will be v11 for a fix.

**Comment by StrayCargo** [comment]
I am encountering the same issue

**Comment by NachtRaben** [comment]
Lots of people are encountering this issue, we have to wait on Reika to push out v11 before we can fix it ourselves.
