### ISSUE TITLE
Why is tinker's construct not in the revolution 2 modpack?

### ISSUE THREAD

**Issue by zakman9797** [Haggle1996/RevolutionPack#221]
Ya why is the tinker's construct mod not in the modpack? its used in like every technical/survival modpack out there? plus it has a easier crafting table, and alot more tool types?

**Comment by devanchya** [comment]
This isn't a bug report, it's a feature request.  should be closed.

If you want TiC, there is another harders ore pack with it in it, but the leveling is much harder.

**Comment by snowmanninja** [comment]
Why is this an issue? tinkers is used by every modpack so should be avoided and over shadows other mods toolsets

and rev2 is better without it

**Comment by zakman9797** [comment]
its an issue because this is a survival/technical modpack? that should have it? like every known survival/technical modpack i know has this???

**Comment by zakman9797** [comment]
players are just going to download the mods and throw them in... anyway?

**Comment by Haggle1996** [comment]
Because TiCo is old, played out, and encourages players to miss whole new sets of gadgets and gizmos from other mods. For example (and this is just one mod in the pack), Botania has a better hammer, better lumber axe, better excavator, and better armor. Not to mention many mods have unique and fun ways to obtain enchantments on tools. Other mods provide the same functionality as the tinkers table, too. For that matter, Revolution is about encouraging you to try other mods.

Do you really want to make yet another smeltery, series of casts, and set of tools you make in every single other modpack you play?

**Comment by zakman9797** [comment]
what mod provides the crafting table? i dont want to sit there forever having to replace materials into the old vanilla table?

**Comment by Haggle1996** [comment]
the worktable from Enhanced Inventories is the easiest to acquire.

**Comment by Toksyuryel** [comment]
Forestry worktable, bibliocraft fancy workbench, thaumcraft arcane workbench... just to name a few.

**Comment by zakman9797** [comment]
also whats up with the default world generation?
 all i see is islands? as far as i can see?
