### ISSUE TITLE
get a dc from sink

### ISSUE THREAD

**Issue by t3rraz** [Haggle1996/RevolutionPack#232]
does i have only the issue or others too? 

when i have a torch in my Hand and do a right click on the sink (cooking for blockheads) then i get a dc.

thanks and nice greetings t3rraz

**Comment by Aivech** [comment]
what is a DC? Crash to desktop?

If so, possible duplicate root cause of #220 #228 and #172.

Anyways, we need logs.

**Comment by t3rraz** [comment]
not to Desktop only says an internal Server error, i can click on sink or the cooking table with a torch in my Hand, how i get the whole file on a Linux Server ? with the Screen command i only see the last 20-25 lines

**Comment by Aivech** [comment]
The logs are stored in a folder under the MC directory called "Logs" IIRC

**Comment by Toksyuryel** [comment]
This smells like a NPE...

**Comment by Haggle1996** [comment]
This isn't related to #220.

This is an enviromine issue with it's dynamic replacement of minecraft torches for enviromine torches. These torches are what burns out, sets fire, etc., which is why torches placed during world gen  (recurrent complex structures, villages, dungeons, etc.) don't go out or start fires, unless you pick them up and place them again.

It seems the code that handles right-click interact for enviromine torches only prevents placement for blocks, not tile entities. This has been reported many times on enviromines issue tracker, but it has not been resolved.

Until then, the only solution is to avoid right-clicking on tile entities with a torch in hand. Additionally, do not enable Zyin's HUD torch assist, as this fails to check for tile entities as well. Botania tools, Tool Utilities, etc., seem to provide some sort of check to prevent this.
