### ISSUE TITLE
Cave Dimension is gated behind Mars progression

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#259]
It's been suggested that the Cave Dimension be gated past Mars access, using desh ingots. It was originally intended that the cave dimension be accessible earlier, as a mining dimension. But as ores are much easier there, it seems reasonable to gate it behind landing on Mars.

**Comment by Toksyuryel** [comment]
I would like to stress that this suggestion came from a desire to put reactorcraft ores behind galacticraft so that people would be encouraged to actually mine them on the moon rather than skipping the mod altogether. As I was later informed that reactorcraft ores don't actually spawn in the cave dimension, the reason for this suggestion is no longer valid. If you believe you have found your own reason for wanting to gate this behind mars, then by all means feel free to do so, just know that my own reasoning for it is invalid.

**Comment by Aivech** [comment]
Ores are much easier on Mars and the Moon, if the legends are true...why bother with the cave dimension?

**Comment by Haggle1996** [comment]
The cave dimension is intended as a 'mining dimension'. It's meant to be abused with quarries, boring machines, arcane bores, etc. Ore is easier there than on Mars/Moon.

**Comment by Aivech** [comment]
How many people are going to spend 9 bedrock ingots on getting to the cave dimension when they can get all the ore they want from the moon/mars, which already cost a quite substantial investment in bedrock?

I wouldn't, but then again I seem to be an outlier as far as play style goes.

**Comment by Taraxus** [comment]
I'm not familiar with Galacticraft, so Enviromine was the natural choice for me to play catch-up on Redstone, mostly. That said, nothing about the cave dimension seems overtly broken to me, you still need either night vision and flight, or automatic mining to really abuse it. Bedrock seems like a sufficient gating to me.

Also, this could probably be confirmed quickly by someone who knew what they were doing in Creative, but I haven't seen any Reactorcraft ores at all so far in there.

**Comment by Haggle1996** [comment]
I agree. Closing this one as 'will not implement'.
