### ISSUE TITLE
Creosate Fluid turns to water!

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#271]
if you place creosate fluid on the ground (admittadly with a wooden bucket) and then scoop up the contents with a vial, you get water!  Is this enviromine thinking that creosate is hydration?

**Comment by Haggle1996** [comment]
Probably. You should report the issue to the enviromine tracker.

**Comment by RaineAndrews** [comment]
On it boss!  I'm just waiting for FrozenSoul to do the new update, so I can report it with the latest and greatest changes (who knows, maybe it will be fixed?)

**Comment by GenDeathrow** [comment]
I don't believe this is an enviromine issue. We look for vanilla water, unless they registered something wrong with the fluid or they switched up ID's, there isn't much I can do. Enviromine is sort of in limbo atm because of other projects, but I doubt Funwayguy will put in a check for something that isn't really our issue. Here is our code so you can see it. 

https://github.com/EnviroMine/EnviroMine-1.7/blob/master/src/main/java/enviromine/handlers/EM_EventManager.java#L617-L630

My guess its either that specific mod, or something else perhaps the vial (unless its vanilla glass bottle)?

**Comment by Haggle1996** [comment]
Thank you GenDeathrow for the response. I'm closing this issue as there's nothing I can do about this, and it is, at worst, a minor inconsistency.
