### ISSUE TITLE
EnderIO Farming Station destroys Magical Crops when harvesting 

### ISSUE THREAD

**Issue by Melakion** [Haggle1996/RevolutionPack#30]
I think this is because of a change in Magical Crops. When you left click a magical crop, it used to break the plant and drop a seed. Now it seems that it is not breaking, just harvesting the essence, and goes back to first growth stage. EnderIO Farming station is breaking it expecting a seed back but the crops don't seem to do that anymore.

**Comment by Haggle1996** [comment]
Have you tried enchanting the tool in the EnderIO Farm with Fortune?

**Comment by Melakion** [comment]
The Tinker's Mattock in it has Fortune II

**Comment by Haggle1996** [comment]
I'll tinker with it a bit. Had fortune III on the test tool and had plenty of seeds in the end -- however, there's no guarantee you'll get a seed back every time, so doing it onesie-twosies may result in complete loss.

**Comment by DorinnB** [comment]
I've read this today : Also, if you use EnderIO Farming Station (and possibly MFR planter) for these crops, be sure to edit the MC4 config and set 'seeds replant themselves' to false. Otherwise, the Farming Station will just eat your seeds away from existence.

source : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287451-magical-crops-farm-your-resources-3-2-0-who-stole?comment=3485

**Comment by Haggle1996** [comment]
Thanks! Fixed in 0.8.7

**Comment by punchdarkwing** [comment]
How do i get to the mc4 config and how do i alter it?
