### ISSUE TITLE
Add custom AgriCraft resource crops

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#303]
Agricraft resource crops in default configs are too easy to acquire. Consider an alternative tree, required block, etc., so that this feature can be enabled. Would be interested if anyone has ideas for a fun alternative progression.

https://github.com/InfinityRaider/AgriCraft/wiki/%5B1.2.*%5D-MineTweaker3

**Comment by Haggle1996** [comment]
https://github.com/InfinityRaider/AgriCraft/wiki/%5B1.2.*%5D-MineTweaker3

**Comment by Aivech** [comment]
Maybe make the mutations impossible and force you to use thaumcraft/botania/chromaticcraft to get them in some way?

**Comment by Aivech** [comment]
Thaumcraft infusion of vanilla seeds with 4 (resource), 2 terrasteel, and 2boosted shards of the nature/growth aspect?

**Comment by Aivech** [comment]
since once you get one you can spread them indefinitely

**Comment by devanchya** [comment]
I don't mind crops as long as they are very hard to get over time. otherwise you end up with giant plant farms with people not moving.

**Comment by corvisrex** [comment]
Take a page from Regrowth, and use Botania's runic altar to make the seeds.  If you can remove the normal recipe/mutation (can you do this in mine/modtweaker?) you can then make it as time consuming and expensive to get the seeds as you wish.

**Comment by NachtRaben** [comment]
Basic magical seeds using botania altar and thaumic based seeds use infusion?

**Comment by Aivech** [comment]
IIRC the resource seeds are only vanilla ores. Since resource crops are kind of magical in nature, I suggest making them require a combination of ingredients from CrC, TC, and Botania. 
(From above: My suggestion was Thaumcraft infusion of vanilla seeds with herba + an appropriate aspect [metallum for iron, sensus for lapis, lucrum for gold, etc.] and two terrasteel, two boosted green shards, and four of whatever the crop would produce [iron ingots for iron seeds, etc.].

**Comment by RemedialTester** [comment]
But instead of just boosted Green crystals, from CrC. How about some other boosted crystals as well, that are related to said resource in question? As Brown seems to be related to most mined resources. Other Themes I've notice are, that resources related to wealth like Gold have Purple, but more rarer ones also have White, such as Diamonds and Emeralds. And Energy/Power is Yellow, Like coal and Redstone.

I know this is covered by the TC aspects, but only one type of CrC element just means we can Infuse a pool of liquid Chroma with an element, boost a stack of crystals at once, and be done with it, for all the seeds. But even then doing this wouldn't improve it all that much, as all that would do is add extra cycles of boosting crystals. Also thought of using Aura Ivy, Nature Fibers or Enrichment Vines. But the former grows too fast and the latter too easy to craft, to make it all that harder.

**Comment by Aivech** [comment]
I was thinking green crystals for the nature/growth aspect. And nothing in Chromaticcraft really is that expensive, it just takes time to get due to the progressinve nature of the mod. Yes, there are some expensive items, but by far the most expensive part of Chromaticcraft is not the items you make but the infrastructure required. 

In addition, all that is required for everyone on a server to get a resource seed is for one player to get one. They really aren't that expensive.

**Comment by oxinabox** [comment]
What if resource crops had SpreadChance 0?
So you can not duplicate them through crop sticks?

(I guess duplicating them with pruning might still work, but well at least that would force people to deal with the more advanced agricraft mechanics)

**Comment by Haggle1996** [comment]
As bees were added as a source of resources, I'm going to close this. I may revisit it in the future.
