### ISSUE TITLE
Crash on clicking Thaumcraft aspects in NEI or Book

### ISSUE THREAD

**Issue by crawln45** [Haggle1996/RevolutionPack#338]
Seems if you click on an aspect in NEI or even the book from what I can tell. If the aspect is "Aspect -1:1"
It crashes the client.

[Screenshot](http://i.imgur.com/cMf2vbr.png)
[Crashlog](http://pastebin.com/x2FAYm8H)

**Comment by sapid** [comment]
Couldn't reproduce in singleplayer. It looks like if the Ichorcloth research is not known NEI won't show this recipe in the first place. I granted myself all research with `/tc research <playername> all` which let me see the recipe in NEI. 

Rather than -1:1 for the Ordo item ID (which is probably an erroneous item ID) I got 7040:1. Clicking on it showed me the ThaumcraftNEI page for Component: Ordo.

**Comment by Haggle1996** [comment]
Can't reproduce with v12.
