### ISSUE TITLE
Pickaxe of the Core not working with Harder Ores

### ISSUE THREAD

**Issue by mtesseracttech** [Haggle1996/RevolutionPack#347]
The prospecting function on the pickaxe of the ore doesn't see any of the harder ores. It would be nice if this worked, to have an underground alternative for prospecting at some point.

**Comment by Aivech** [comment]
For now, the Rod of the Plentiful Mantle should work.

**Comment by sapid** [comment]
I suspect the fix for this is adding appropriate aspects to Harder Ores.
https://github.com/Azanor/thaumcraft-api/blob/master/ThaumcraftApi.java#L103

Should aspects scale with hardness? Probably so. Possibly up to 4x aspects? Expected output from a hardness 15 ore has an expected output of 3.5 ingots, right? For reference, normal ores have...

Coal: 1 Ignis, 2(?) Potentia, 1 Terra
Iron: 3 Metallum, 1 Terra
Gold:
Redstone: 2 Machina, 3 Potentia, 1 Terra
Lapis: 3 Sensus, 1 Terra
Diamond: 3 Lucrum, 1 Terra, 3 Vitreus
Emerald: 4 Lucrum, 1 Terra, 3 Vitreus

(Electricraft)
Platinum: 6 Lucrum, 2 Metallum
Aluminum: Nil
Nickel: 1 Metallum
Silver: 1 Lucrum, 3 Metallum, 1 Perditio
Tin: 3 Metallum, 1 Perditio, 1 Vitreus

(Galacticraft)
Tin: See above
Aluminum: Nil
Silicon: Nil
Copper: 2 Metallum, 1 Permutatio, 1 Terra

A little further testing suggests that these are ore-dicted aspects.

**Comment by sapid** [comment]
Oh, MineTweaker supports Thaumcraft. That's probably a much easier way of doing it, once scaling is decided on.

http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thaumcraft_4_Support

**Comment by DragGon7601** [comment]
I've made a mine/modTweaker script that adds the aspects to the ores. This does seem to make them work with the pick. Let me know if I missed any ores or messed up the aspects.

[Ores-ThaumAspects.zs.txt](https://github.com/Haggle1996/RevolutionPack/files/310597/Ores-ThaumAspects.zs.txt)

I noticed that most ores get 3 points of Metallum and 1 of point in 2 other aspects. Because of this Aluminum was given 3 Metallum and a point in aer & motus because it is a light weight meterial used in allot aerospace.

I Think Nickel should be buffed to keep it in line with other metals but didnt do this as I didnt want to overstep any lines.

I also added aspects to any ores I seen that didn't have them. 

The down side of how thaum and harder ores work is that each meta is a different block so you can rescan it and get more aspects for research. But then your have to scan 16 times so... yeah its not OP IMHO.

**Comment by Haggle1996** [comment]
Nice! I'll get this added.

**Comment by DragGon7601** [comment]
I Errored, and didn't think that ore_limonite & ore_uranium spawned... Knew ore_osmium didn't, but I've since rechecked that. Here is an updated file:

[Ores-ThaumAspects.zs.txt](https://github.com/Haggle1996/RevolutionPack/files/310607/Ores-ThaumAspects.zs.txt)

As I didnt have MC open at the time, these are more likely to fail. And the aspects where based off what I thought rather than what was in game. Limonite is Iron with aqua because it spawns underwater. A uranium is lucrum 2 (greed, wealth), potentia 2 (energy), venenum 1 (poison). Sorry if there is any issues with this one.

**Comment by Haggle1996** [comment]
This has been added.
