### ISSUE TITLE
Quick stack in an Enhanced Inventories crafting table causes hang.

### ISSUE THREAD

**Issue by Kreidos** [Haggle1996/RevolutionPack#400]
Pressing the quick stack (aka Quick sort) key while in an Enhanced Inventory's crafting table will cause the client and server to hang. Killing the client process will allow the server to recover. 

Steps to reproduce: 
With an enhanced crafting table interface open, and items in both the crafting inventory and the player's inventory, press quick stack.

This issue will cause lock-ups while searching NEI while in an enhanced crafting table, if the quick stack key is pressed.

**Comment by Kreidos** [comment]
As this is an interoperability issue between Enhanced Inventories and Zyin's HUD I'm not sure who this should be reported to upstream.

Since using the middle-click InventoryTweaks sort in an EI crafting table causes a brief client hang, I suspect it's that the EI inventory management has a large overhead and quickstack requires a lot of individual operations.

**Comment by Haggle1996** [comment]
The quick stack from InventoryTweaks works for me (though with a slight delay). The Zyin's HUD stack occasionally hangs. It's disabled by default in the pack, so I'm not sure there's much else I can do. Zyin's hasn't updated in a long time. I'm going to close this just because of my OCD nature (closed means I'm not going to do anything more about it, not that it is no longer an issue), but I'll keep an eye out for updates from the author.
