### ISSUE TITLE
Diamonds / Emeralds gone after Rockhounding removal

### ISSUE THREAD

**Issue by mayonnaisefarmer** [Haggle1996/RevolutionPack#404]
Rockhounding overwrote the vanilla Minecraft diamond / emerald ore, meaning the Rockhounding removal strips already generated worlds of two pretty precious resources. To me, it makes more sense to keep the previous version of Rockhounding in the pack and update it later when there is a clear stable release that keeps worlds compatible, or something similar. As is, you've made worlds semi incompatible just by removing the mod :/

**Comment by Haggle1996** [comment]
Given the rarity of rockhounding emeralds, they weren't easy to find.

Natural emeralds can be found in the mining dimension as well as created through several magical means.

EDIT: Diamonds were never naturally occuring to begin with; the Harder Ores diamond ore is present.

**Comment by mayonnaisefarmer** [comment]
I've also noticed that a lot of tunnels in the world after the removal instantly cave in when interacted with. I'm also a bit upset that my entire world is basically borked because my entire house and everything nearby was made with rockhounding brick :c I'm sure you have your own reasons for not keeping the latest stable release of the mod though.

**Comment by Haggle1996** [comment]
I'm not sure what qualifies as the 'latest stable release'. Back in 3.x days, with all the fun options turned off (chemistry, jewelry, etc.) so that the mod was only decorative, we still had bugs and crashes just doing basic things.

The mod author has not released a version in which blocks have not been renamed, causing world-loading corruption. As a pack developer, it's extremely frustrating when the mod author leaves you with only two choices of either upgrading the mod to fix world-corrupting bugs (and in the process, corrupting existing saves), or not upgrading and leaving the world-corrupting bugs in-place. Not the best situation either way.

As a pack author, I try exceptionally hard to insure pack versions are backwards-compatible -- many pack authors don't even bother (or don't maintain their packs). It's a lot of work on a weekly basis for which I receive no compensation. And like you, I'm at the mercy of mod authors.
