### ISSUE TITLE
OpenGL Error

### ISSUE THREAD

**Issue by TheGamingTale** [Haggle1996/RevolutionPack#406]
Every time I try to go on a server with the Revolution 2 pack it comes up with this error - 

Internal Exception: java.lang.RuntimeException: No OpenGL context found in the current thread.

Does anyone know how to fix this?

**Comment by Haggle1996** [comment]
OpenGL errors are almost always related to graphics card-related errors. Make sure you have the latest drivers for your card and reboot your system and try again.

If you are running OptiFine, try loading the pack and connecting with OptiFine removed first. If it works, try reenabling Optifine and attempt to connect again. One of OptiFine's installation steps is to start your instance once without it, then restart it with OptiFine added. This changes the load order of OptiFine.

Occasionally, it can be caused by a mismatched set of mods with the server. Make sure you have the EXACT same set of mods. If the server admin publishes a share code, make sure you're using that.

**Comment by TheGamingTale** [comment]
Ok thanks

**Comment by RaineAndrews** [comment]
I second the GPU driver update.  Don't ignore doing this, as it fixes so many issues!  If none of this is working, try updating [LWJGL](https://www.lwjgl.org/download).  Have you been able to connect in the past?  Did you recently do a java or windows update?

**Comment by Haggle1996** [comment]
#410 also has a bunch more info on troubleshooting OpenGL errors. Regardless, this is not a pack issue but a machine issue.
