### ISSUE TITLE
Silver indicator?

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#407]
I've explored many maps extensively, and have yet to find silver indicators.  Is this because silver is deeper than other ores, because mountains have less plantable ground, or because they don't spawn at all.  I used cogEnableDebugging and I can confirm its generating for me, but there are no flowers to indicate it's presence.

**Comment by Haggle1996** [comment]
Silver is disabled, at the moment, along with the other non-vanilla ores except for copper. However, I've noticed that nickel flowers still spawn naturally. Silver has always been rare, as it spawns really deep (same for diamond, emerald, etc.), and are usually only found in the lower elevations.

The best method I've found to get these ores (prior to the wand of the plentiful mantle -- you should really craft one) is to take a stack or two of bonemeal and randomly spawn grass as you travel the world. You'll be surprised what pops up.

I was actually in the process of re-enabling these flowers for v2.7 when you reported the issue, since the memory issues have been fixed. :) Obviously, this won't affect already-generated chunks, but will be better for new players.

**Comment by RaineAndrews** [comment]
Any chance COG has a retrogen of flowers option?  I'd hate to make yet another world :P

**Comment by Haggle1996** [comment]
It's actually Harder Ores, not COG, and no, it doesn't have a retrogen option.

Really, it's not that hard to find ores. A rod of the plentiful mantle makes them very easy to spot and can be crafted early game, assuming you find a diamond in a chest.
