### ISSUE TITLE
How to fix 'maximum id range exceeded' errors when upgrading to 2.7.1.1 or later

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#428]
When upgrading from earlier versions of REV|2, players receive a message that two ExtraUtilities blocks have been removed. This is normal and should be accepted/confirmed. Some players then receive `Forge Mod Loader detected that the backup level.dat is being used.` Continuing/accepting results in a corrupted world and the following line in the fml-server-latest.log (or fml-client-latest.log):

`
[22:29:39] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: Invalid id 7263 - maximum id range exceeded.
`

Unfortunately, this is a result of the frequent block renames caused primarily by (but not exclusively by) the Rockhounding mod previously removed. You can read more details about Forge's handling of block renames [here](http://www.minecraftforge.net/forum/index.php/topic,27908.0.html).

There is a relatively easy fix, which will allow you to upgrade your map and continue playing; **however, be warned that SMP players may encounter issues with player inventories for players who have not logged on PRIOR to the 2.6 update** There is the potential that their inventories are corrupted, so it is best to delete their related files from the playerdata folder. SSP players should not need to worry about this.

Follow these steps to fix the issue:
1. Revert your save to the version 2.6 backup. If you are on 2.5 or earlier, upgrade to 2.6 first.
2. Load up the level.dat (located in your /world folder on SMP or appropriate save folder on SSP) using your favorite NBT editor (I'm using NBT Explorer in the image below).
3. Open up the `FML/BlockedItemIds` tag and remove all IDs. Yes, there's a lot of them. NBT Explorer should say '0 integers', as pictured.
4. Save the level.dat
5. Run the update process and confirm the removal of the ExtraUtilities portals.
6. Play.

![image](https://cloud.githubusercontent.com/assets/11808184/15490388/bcca27ce-2124-11e6-86e2-cb7c86757231.png)

**Comment by DragGon7601** [comment]
If I understand right each rename causes it to use an extra Id but didn't free up the old Id's for use by new mods, and even removing the mod does not free them up... Your guide fixs the problem and frees up those Id's. But requires the use of a NBT editor, something that maybe scary for less technical users.

I have another option, that may not work. Shouldn't harm to try it, but always back up first. It only needs the user to add a mod. 

[NotEnoughIDs](http://minecraft.curseforge.com/projects/notenoughids)

It wont truly "fix" the issue but should let the world be played with no side effects. It simply extends the ID array so that you dont run out even though so many of them are still "in use" by the removed mod.

It is best to follow Haggles guide if you can... But if you lack the computer knowledge/skill and/or the courage to learn them; then this option may work. I offer no warranty.

**Comment by Haggle1996** [comment]
I've added NotEnoughIDs to the next update, which seems to address the issue without resorting to NBT editing. I'm going to close this issue. Players who don't want to mess with their NBT can wait until 2.7.2.0 to upgrade their instance.

Thanks for pointing the mod out, @DragGon7601. I knew about the mod, but hadn't connected the dots. :P
