### ISSUE TITLE
Make RFTools more accessible mid-game

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#438]
RFTools has many features that are useful in the mid-game that are not overpowered. Currently, everything is gated post-bedrock. 

Consider moving many of the devices before bedrock, but leave the interesting dimlets to phenominal cosmic power levels.

**Comment by Kreidos** [comment]
If so, machine frames and bases could be made of inductive ingots instead of bedrock.

Currently it doesn't appear that RFTools dimensions are possible without an admin spawning in an owner dimlet anyway. I grepped through all the configs and scripts looking for an alternate way to get them, but wasn't able to find one.

**Comment by Toksyuryel** [comment]
The standard way to acquire your first dimlets is to either find them in loot chests throughout the world, or to find them in structures that generate in dimensions you create (from the basic set of craftable dimlets.) To create the rarer dimlets you first need to find a dimlet of equal rarity and tear it apart for components. It'd be a good idea to read the RFTools Dimension book to learn how finding and creating dimlets works.

**Comment by Kreidos** [comment]
Thank you, but I'm well aware of where dimlets come from. I was referring to the special "Owner Dimlet" which can only be spawned in by an admin. If [this config flag](https://github.com/Haggle1996/RevolutionPack/blob/revolution2/config/rftools/main.cfg#L206) is true an "Owner Dimlet" is required  in order to create a dimension in the dimension enscriber.

This acts as a way to limit who can have dimensions, and how many, on a server.

**Comment by Haggle1996** [comment]
I've removed the owner dimlet requirement. Server operators that want to limit player-created dimensions should change this rule.

**Comment by Haggle1996** [comment]
I've also reduced the material requirements of the machine frame and base, gating the frame after inductive ingots (which is after jet fuel).
