### ISSUE TITLE
skip night and bloodmoon

### ISSUE THREAD

**Issue by DorinnB** [Haggle1996/RevolutionPack#445]
Cryogenic chamber (from galactic planet ?) allow you to skip night and bloodmoon.

_exploit : we can skip night and bloodmoon. Information on twitter (I know those damn coward who will use it before the next update ! so I won't tell it here)_
You're right, sorry

**Comment by Kreidos** [comment]
I fail to see the point in keeping bugs a secret.

98% of players likely don't even know this Github exists, or will never look at it. Way more people use twitter.

Also, if someone is determined to avoid bloodmoons, they'll just turn them off in the configs. It's a lot easier than finding some bug.

**Comment by Aivech** [comment]
What is the recipe for the cryogenic chamber?

**Comment by DorinnB** [comment]
desh and meteorite.
Tiered to mars i think.

**Comment by Aivech** [comment]
I'd say getting to Mars is a pretty worthy accomplishment...

**Comment by Haggle1996** [comment]
As a pack, I don't intend to remove this item, as it's been presented as a way to skip a bloodmoon for end-game. 

As a server operator, you may feel it's unfair since it resets bloodmoon/night for all players. In which case, I suggest removing it's recipe through minetweaker (or add it to the banned items list if you're using server software that allows for that). There's several methods in the pack, including Draconic Evolution and Thaumcraft add ons that allow players to control time.
