### ISSUE TITLE
draconic & wyvern armor need diamond armor

### ISSUE THREAD

**Issue by DorinnB** [Haggle1996/RevolutionPack#465]
Both need vanilla diamond armor. They are disabled.

Is it intended or do we have to change the recipe ?
hsla armor or diamond bloc may be ?

**Comment by ghost** [comment]
Both being wyvern needs diamond and draconic need wyvern?

Draconic Evolution uses Diamond armor by default. Haggle must've forgot to change it to use a different armor. 

Personally, I hope it doesn't use bedrock since draconic armor is more op, yes, but has it's flaws. Like needing a ton of RF and with no real good wireless chargers it's a pain. Not to mention that making an unbreakable rock change material and be powered by RF doesn't really make sense. Making a gem/metal another material that is probably a metal itself makes a LOT more sense.

**Comment by DorinnB** [comment]
well, my bad. Wyvern need diamond (and draconic need wyvern) but as gold armor for ichorium, diamond armor **can be looted on mob.**

I forgot mobs could drop diamond armor. Not so hard,after 10 minutes deep inside a donjon I had a full broken set. I've used with some repair tool and voila.

**Comment by Aivech** [comment]
> no real good wireless chargers

EnderIO. Also, DE has it's own charger that can charge about as fast as you can pump power into it.

**Comment by ghost** [comment]
Last time I checked, EnderIOs charger was broken as it charges EVERYONE on a server and not just a placer/area. Additionally, DEs charger is not wireless.

**Comment by Toksyuryel** [comment]
I have never experienced the EnderIO wireless charger having infinite range. Perhaps you were playing with a bugged version or a faulty config?

**Comment by ghost** [comment]
Unlikely, it did this twice through two server reboots and the version has been updated several times.

**Comment by Aivech** [comment]
I am almost certain the range is dependent on the amount of power available to it. Thus, with enough power to charge draconic evolution armor in a reasonable amount of time, it could have a range sufficient to cover an entire server.

> DEs charger is not wireless.

Random Things has a player interface - you can use it to access your inventory with infinite range with the piping system of your choice. Works across dimensions as well, IIRC.
