### ISSUE TITLE
Crash when placing the second of a pair of world rifts

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#466]
Crashlog at http://pastebin.com/ftW2hL3c

This happens whenever I place a world rift, and there exists an unlinked one in the world that the current one attempts to link to. After re-loading the world, the world rift is placed and linked correctly. Sometimes the link attempt will not be made, then the crash does not happen.

I tested this with a new instance of Revolution 2 with JourneyMap and all optional mods except BetterSleeping and Rockhounding, in a newly-created BoP-type world, and it is perfectly reproducible. 

Reika says he can't reproduce this, so I assume it's a modpack problem.

**Comment by ghost** [comment]
Is it really necessary to post the same thing on two different [issue trackers](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/987)?

**Comment by Haggle1996** [comment]
I encourage my pack players to report issues directly to the mod authors first, then to report back here if it turns out to be a pack problem. Unless you work with GitHub regularly, most people don't know you can reference an issue on another tracker simply by doing owner/repository#issue...for example ReikaKalseki/Reika_Mods_Issues#987.

Unfortunately, network errors are notoriously hard to debug -- the mods mentioned in the stack trace are not always the ones at fault. Frequently, there will be a separate error on the server log that's completely different from the crash report.

If that error is not helpful, really the only way to test this is to start ripping out mods until you come to a minimal modset in which the behavior still occurs. I have a hunch this may be single-player only, as we've had multiple world rifts in a server environment working just fine -- but again, it's one of those things that are going to take a lot of time to debug.

**Comment by Ieldra2** [comment]
So...if I run a server on a separate machine and connect to it as the only player, rather than play SSP, the problem may disappear?
Also, if the problem appears again, I guess I should check the server log...

@HyperionNexus:
Reika closed the issue on his tracker, but it nonetheless exists. What else could I do?

**Comment by Haggle1996** [comment]
It may be an issue with open computers; you could try disabling the mod, see if it still occurs. I'll test it sometime between now and the weekend.

EDIT: I was testing earlier with the updated OpenComputers while working on the next, so this may already be addressed.

**Comment by Haggle1996** [comment]
With latest OpenComputers and v15 of Reika's mods, it's still crashing placing the second rift.

**Comment by Haggle1996** [comment]
Fixed in the next update
