### ISSUE TITLE
Suggestion: Make RTG optional

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#477]
Rationale: It appears that RTG adversely affects Ocean Temple spawns even in BoP worlds if it's loaded, just in the same way that RTG's "inventive" biome registrations make it impossible for void reed to spawn in swamps, even if you don't use RTG terrain generation. A mod with effects that prevent progression in another mod should not be required.

**Comment by Haggle1996** [comment]
The previous known issues with Climate Control and RTG have been fixed in the forthcoming pack update. For example, Void Reeds now spawn in swamps, and Climate Control stops doing the funky biome selection (technically, the Void Reed issue is a problem with BoP, it was just fixable via RTG/CC). I've also got it correctly set now so neither mod interferes with non-RTG worlds when they are selected in the world type drop down.

And then there's the other problem: BoP doesn't play well with CoG, and CrC unless RTG/Climate Control is installed. For example, boring machines and bedrock breakers cause incorrect world gen. Certain CrC flora doesn't spawn because BoP overrides the biome generator, causing CrC to ignore the biome.

I'm more likely to remove BoP than I am RTG/CC.
