### ISSUE TITLE
Suggestions: Buff Diesel Generator and Plant Oil Production

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#495]
Revert the change to the Immersive Engineering Diesel Generator to its original output of 4096 RF/t, which will make is competitive with Rotarycraft Performance Engines on a power/cost basis.

Add a recipe to the Immersive Engineering Squeezer to create plant oil from canola seeds with a tentative value of 5-10 mB of plant oil per canola seed. This will provide an alternative use for excess canola.

**Comment by Ieldra2** [comment]
Anything that makes the Diesel Generator more attractive is good, but small adjustments won't do it. Consider that a chain of 4 hydrokinetic engines generates 4032 RF/t. The main problem is that IE steel is tedious to make at the point where you would want a Diesel Generator, which makes it not just the most expensive machine to generate that amount of RF, but also the most time-consuming to build _and_ the one that needs the most complex processing chain for its fuel. 

There's also a fundamental problem: In terms of Immersive Engineering's progression, the Diesel Generator is high-end, which is why the complexity is justified. In terms of the Revolution Pack as a whole,  however, it's a mid-game machine, and not even a particularly powerful one considering that you can't even run a medium-sized ME network with the shaft power equivalent of 4000 RF/t.

So, in order to make the Diesel Generator competitive for mid-game power generation in Revolution, you'd have to increase its power output to...hmm.. at least 8192 RF/t, perhaps even 16384 RF/t. That would be approximately equivalent to 8 MW of shaft power, which in my experience, is the output of a typical mid-game power plant. Give it significantly less, and it'll be so much more efficient to convert shaft power to RF rather than build a Diesel Generator that players will only build one because they absolutely want it.

**Comment by Aivech** [comment]
Also keep in mind that one properly supplied refinery making biodiesel can run ~3 diesel generators, that in general IE machines look really cool, and that you could probably automate steel fairly easily.

**Comment by Ieldra2** [comment]
Automation is not a problem, but rather the time it takes to make steel before you have an arc furnace. Between "I want to build a Diesel Generator" and actually building one is a long time spent for making steel, whether automated or not. HSLA steel is so much easier to make in quantities that it puts significant weight into the option "Make RoC stuff and convert to RF".

**Comment by Haggle1996** [comment]
What do you think about reducing the amount of time it takes to produce IE steel? Maybe more in line with the time it takes to produce HSLA steel?

**Comment by Haggle1996** [comment]
I've resolved this by 1) reducing production times of steel and coke 2) increasing diesel engine to 8192 rf/t 3) making plant oil squeezable from canola 4) rebalancing a number of IE devices (details will be in the changelog)
