### ISSUE TITLE
Crash after pregenning chunks

### ISSUE THREAD

**Issue by vcordie** [Haggle1996/RevolutionPack#50]
Every time after I pregen spawn chunks, after completing gen it will crash, without fail. 
http://paste.atlauncher.com/view/4807f613

**Comment by Haggle1996** [comment]
This happens randomly with particular world seeds. It's safe to reload and continue. It happens more often with positive seed numbers and when you've chosen a default world instead of ATG. 
Unfortunately, the mods that cause the concurrent modification exception are the mods that give the pack its look and feel. A couple are no longer maintained by the authors.
