### ISSUE TITLE
Modpack install error

### ISSUE THREAD

**Issue by jusvit** [Haggle1996/RevolutionPack#508]
Might just be me, but I've tried installing the modpack (latest rev3) on two different computers on two different internet connections.

So when installing it ( i chooose install optimal mods)  whenever the downloader get's up to downloading
journeymap-1.7.10-5.1.4p1-unlimited.jar

it fails, and i have to manually get it from curse and put it into the downloads folder.

**Comment by Haggle1996** [comment]
The link I pull from is http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

I don't know if you're the same person who reported it on MCF....I cleared my atl cache and it downloaded fine. Perhaps curse had a problem? Wouldn't be the first time. Unfortunately, JourneyMap is the only mod I have to always pull directly from Curse instead of nodecraft's content network.
