### ISSUE TITLE
Lots and LOTS of lag.

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#523]
So me and my friends get the modpack (Revolution|3) and install it onto our server, we get on and I am happy to notice I have 109 FPS. Problem is we all are lagging for some reason... Like really bad... This hasn't happened on other modpacks this big so what is the problem? (We also knew it wasn't our connection to the internet) EDIT: At least we knew OUR connection to the internet was good... Does it have to do with us reaching the server?

Video: https://youtu.be/V6yMhtJ7ePM

**Comment by CodingManDan** [comment]
Where is your server located? I have seen lag like that once when I set up a server on the other side of the planet (I didn't know it was located there at the time).

**Comment by Haggle1996** [comment]
There are a number of reasons for really bad lag, and I can't do much for you other than suggest some things to look at.
- If it's a fresh server, make sure it has enough memory allocated. Generally, no less than 4GB -- 6 is better.
- Try restarting the server, if you haven't already. 
- Try pregenerating the world. World gen is expensive in Revolution, due to the huge veins which can span hundreds of blocks. With too many players running off in new directions on a fresh map, it often overloads the world gen of a non-pregenerated world.
- If it's an established server (meaning, you've been running the map for a while), you'll need to use a tool like Opis to diagnose what's at fault.

**Comment by ghost** [comment]
I think it might be the first problem @Haggle1996
