### ISSUE TITLE
The RFTools water dimlet is only 2rf/t

### ISSUE THREAD

**Issue by AshIndigo** [Haggle1996/RevolutionPack#596]
This makes acquiring water pretty trival which breaks the pack to a certain degree.

**Comment by DragGon7601** [comment]
First you have to be lucky enought to get it... And you will likely want some other dimlits, like single biome or such so liquid pools are large & common. Then you have to have built some machines to make the dialling device and teleporters and be able to feed them with enought power to get there (And more to get back if you dont have another way). 

Then your going to set up some way of collecting the water and you likely want this to be unmaned/automated. Then get it back to the overworld... And as to automating that, you could use a bottler it and put the filled bottles/buckets in a enderchest and... Is there an un-bottler? Or if your late enough I think the dimentional rift maybe able to send liquids between dimentions.

All this so you can avoid setting up a water gen system or draining an ocean in the over world. Like a few Railcraft watertanks, or a Dew point thingy. 

Yes the Dew point thingy needs power, but using ender IO cables, Witching gadgits coble gen feeding a Ender IO sag mill (to make sand), a composter to make dirt, A 7x3 fan havisted sugercain (10/10/10) farm, 2 Pams pressers (sugercain into suger), 3 fermenters, a furnace run by the chroma Heating thing and likely a few bits and bobs I cant remember but would be easy to guess if you tryed to set it up yourself... I have a room that I feed only water into (a single Railcraft water tank would be enough) and get an endless supply of ethonal crystals out! I havent tested it yet but Im sure it will keep up with several engines running constantly. I was running a grinder, an extractor and the Jetfuel making making machine off of it and it easily keeped up. 

Basicly by the time you can set up the use of the water dimlet you have other options that would work just as well. Automated fuel production is likely something you will want to do anyway & expanding it a little to run a DPA or 2 isnt as much of a hassle as setting up the RF Tools dimention IMO. By the time you have enough tech to make the RF tool dimention worth it, its just another reward for having got that far in the pack.

So any breakage caused by this dimlet being cheep is not worth worrying about.

**Comment by Haggle1996** [comment]
I agree with @DragGon7601
