### ISSUE TITLE
Connection lost "timed out"

### ISSUE THREAD

**Issue by jhighjo** [Haggle1996/RevolutionPack#620]
Hello
Somedays it is impossible to me to connect on my server without having the message " connection timed out " I appear in game some moment without any block, and the game disconnect. 

log client : http://pastebin.com/aXBnqifY
log server : http://pastebin.com/yrHDPwva

Sorry for my bad english :p

**Comment by Kreidos** [comment]
Yep, the connection timed out; the server didn't respond in time. Usually it's because the server is overloaded or busy doing something else.

I don't think this is caused by an issue with the pack and this isn't the place for technical assistance; it's for reporting bugs. Technical support should be sought through the [IRC](http://webchat.esper.net/?nick=&channels=Revolution) or the [Minecraft forum thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mod-packs/2411393-revolution-3-a-rotarycraft-chromaticraft-themed).

**Comment by jhighjo** [comment]
Oh ok, sorry for that!   You think that comes from the host?  at beginning the technical assistance from my server say " the server is ok but your modpack...."
Thanks a lot Kreidos

**Comment by Haggle1996** [comment]
These more commonly occur when there's a mod mismatch between the client and server, particularly when the client has some optional mods that the server doesn't, but could run on both. For example, you'll get this if the client has MCHeli, but the server  doesn't.
