### ISSUE TITLE
Advanced Rocketry Select Planets all planets except earth and moon are gone

### ISSUE THREAD

**Issue by Grundolt** [Haggle1996/RevolutionPack#627]
I can't select any planets other than earth or the moon as a destination.  the << UP button won't work.  Can't look at any other planets in the system map.  If I select the moon then the << UP button works to get back to the Earth/moon view, but from there it won't back out further.

  /advancedRocketry planet list lists all the planets in the sol system...quite a few.  But the rocket select destination button only sees earth and the moon.  

When I check other save files I have the same problem.  Even on my creative world where I am currently on another planet, I can't see or select anything but earth or the moon.  I tried reinstalling the modpack.

**Comment by Gamerthekid** [comment]
It most likely is because you have not made the tier 2,3..etc rockets yet.
You need to make these rockets first and fly with these rockets to get to
the more advanced planets. This would explain why /advancedRocketry worked
to see all the planets but when you select the rocket destination you can
only go to the moon or earth.

**Comment by Haggle1996** [comment]
Closing for now, there's a lot of changes to Advanced Rocketry in the next update.
