### ISSUE TITLE
Remove infinite water supply

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#80]
Infinite water supply provides water at any flow rate -- needs to be either limited to something realistic, or removed entirely. Dew Point Aggregator is sufficient for reactors (with power). Ender IO reservoirs work for early game.

**Comment by rladams** [comment]
I agree! Nerf it hard!

**Comment by X3nophop3X** [comment]
If you are referring to pressure pipes I must say please don't remove them entirely even if you nerf them. While DPA's will work for small to medium size reactors, larger ones (like the one I am running) become problematic. The arrays become so large that space and oversight become a next to impossible. Not to mention the fact that I don't see how a fusion reactor build in survival would even be possible anymore. Every YouTube video I have ever seen with a fusion reactor is done in creative where the builders run around with magic wands filling up numerous reservoirs as they see fit creating as many infinite water supplies as necessary. Lastly, I thought that the whole point of adding the mod was to make large reactor builds in survival, realistic and fun! Water is not the only requirement to run a fission or fusion reactor, the challenges are numerous, i.e. finding magnetite. The lubricant requirement for just one High-Pressure turbine alone is astronomical not to mention feeding three more I plan on building (one day). So the challenges are still there to say the least.

**Comment by Haggle1996** [comment]
Thank you for the comments. I past my talk list here just for that reason, to elicit feedback before I make the change

-----Original Message-----

**Comment by rladams** [comment]
I disagree. I built a strong reactor in a finite water world (no springs) on our last pack, and using a DPA and a fluid compression chamber it was trivial to guarantee enough water was always available to the reactor. I only ran them when the FCC got low (25% of 1,000,000 buckets) using Electricraft. Even if you don't cache the output, a DPA with several MW of power can keep up with any water need. It was even buffed to hold 128 buckets in an internal tank where before it kept 4 or 10.

**Comment by X3nophop3X** [comment]
riadams, I am sure you are right, your set up sounds all very do-able, even for me. I have the power - two auroral batteries and some lower tier ones as well. I wouldn't say I'm  lazy but perhaps over stretched a bit. I'm playing single player so no help and no logging off and waiting for your canola farms to produce oodles and oodles of seeds while the server runs. I guess what I am saying is the the pressure pipes infinite water source helps keep things neat and realistic for me. Oh, and btw there is definitely a limit to what those things can do. I have a 1200 block canola farm broken up into four sections which in turn are broken up into two. I am running a mere 12 sprinklers with RoC liquid pipes off of one pressure pipe set up with infinite water. The four sprinklers on the end of the system only run about 50-60% of the time because the required pressure of 100kPa's is not met. So there are limits, it is definitely not a god mode water source.

cheers

**Comment by X3nophop3X** [comment]
Haggle, I retract what I said about magnetite being hard to find. I reset my moon today and Wow! I'm swimming in the stuff now, although it may take a while to collect all that I need. I have my extractor running at one operation per tick now processing ores is a a blast. Just sit back and watch it process dozens of stacks in seconds!

I haven't said it before so I'll say it now. Great job with the mod pack! I can see you have put a lot of thought and time into it. I really enjoy playing it. I have been mostly concentrating on Reika's mods (except Chromacraft, I can't really get started with the info-fragment thing) but I know there is much more to it than that. Keep up the good work.

cheers

**Comment by Haggle1996** [comment]
I am removing the crafting recipe for Infinite Water Supplies, rather than removing the block entirely. This will prevent unexpected 'uh oh, why isn't my reactor getting water?' situations in updated instances of the pack, while keeping new players from making them. Server admins will need to determine their own schedule for removing the block from their server.

**Comment by X3nophop3X** [comment]
So I am having major difficulties getting water to my reactor. My base is in a mountain y level 72 to 52, not so terribly deep. The temperature for a resting fuel core reads 32 degrees even though I am bordering grassland and tundra. The DPA placed right next to a fuel core reads 10 degrees. since the DPA needs to be cooler than the surroundings no amount of cooling fins will ever get it cool enough to work. Bringing in water from a distance is problematic because of the pressure drop off over distance with the RoC liquid pipes, which are by the way the only pipes of which I have tested that have a high enough volume to feed the boilers. Also my reactor runs very very hot. Its a tritium producer that requires 36 neutron irradiation chambers to be continually working in order to keep the fuel cores from more or less exploding within 10 seconds, so a consistent supply of 1MPa of water in the pipes is critical to keep in running smoothly. Its actually a very good design for producing tritium and I would hate to have to scrap it since I spent days (literally) coming up with the design. If anyone has any suggestions I would be very happy to hear them.

**Comment by rladams** [comment]
Setup the DPA separately at a different height with cooling fins if needed and output into a fluid compression chamber. Use bedrock pipes from the FCC to the reactor boilers, it will not run out. If you can compress enough water in for 1 million buckets, you'll have huge pressures that will burst normal pipes.

**Comment by X3nophop3X** [comment]
ok, so it worked, and i appreciate the help very much so. I was pulling my hair out trying to figure out how to make my set up work. Now I can run my reactor with a high pressure turbine and produce tritium without going Chernobyl. thanks
