### ISSUE TITLE
Reloaded world reverts to old state SOMETIMES

### ISSUE THREAD

**Issue by wugmump** [Haggle1996/RevolutionPack#86]
I can't nail this one down. Most recent public version, all difficulty mods disabled, about 33% of the time the loaded world is one from a previous save.

**Comment by Haggle1996** [comment]
You're not the first to report this -- but I'm having a hard time recreating the issue. If it happens again (or if you still have the logs), can you zip and email to me both the current and previous log? (either fml-server-latest.log and fml-server-3.log, or fml-client-latest.log and fml-server-3.log). Also, can you tell me about your environment? Single player? Server? OS, memory, etc?

**Comment by anwelti** [comment]
Hello Haggle1996,
i got the same Problem. I think it occurs after the first backup from AromaBackup. it occurs when new like old created worlds.
I play in a Single-Player-World with my girlfriend in my world with open LAN-Session. Her inventory is still at correct stand after relog in my reloaded world next day, but my inventory and the world is at stand of last backup.
Then i leave the world, after my girlfriend is went, is going very fast to arrived the main-menu of MC, i dont think the world is saving now.
Enviroment: Windows 10 Pro, 8 GB RAM. 1.0.10 Revolution-Mod (new installed) with recommend mods at delivered setup

Befor 1.0.10 i dont got this Problem.

And sorry for my bad english.

**Comment by Bamseoejne** [comment]
I got the same problem and it has happened twice in a row now where the world reverts back to the previous state.

Enviroment: Windows 10, 12 GB RAM, 1.0.10 Revolution mod (recommended mods added).

Also got some log files I can mail you.

**Comment by Haggle1996** [comment]
Copies of the previous log (fml-server-3.log or fml-client-3.log) would be the most beneficial at this point. They can be emailed to haggle1996@gmail.com

**Comment by Haggle1996** [comment]
I've uploaded a new version of the pack to the ATLauncher (1.0.10.0-FIXTEST). You will need to manually select it from the list of available versions. This version reverts the latest versions of Aroma1997Core and AromaBackup. Again, without logs and reproduction steps, this is a shot in the dark, but it a likely culprit since it affects world save and both client and server versions.

**Comment by Haggle1996** [comment]
I've confirmed the issue is Aroma1997Core/Backup. Specifically, when it does it's first backup, it stops the server thread (to prevent ConcurrentModificationExceptions). After it finishes, it restarts the thread, but FML no longer saves the map to disk every few minutes. Whenever the backup interval occurs (by default in the pack, 2 hours), the map is written, but only then. I will be pushing 1.0.10.1 in a few minutes. Please update ASAP.

**Comment by anwelti** [comment]
It works fine for me ... thx for fast fix
