### ISSUE TITLE
[Botania] Daybloom disapear

### ISSUE THREAD

**Issue by mbbkraft** [Haggle1996/RevolutionPack#94]
I found a new issue : i crafted 12 daybloom to start botania so i let them produce some mana and go away and when i came back i say that all my flowers disapeared so i guess it's an issue because it's not supposed to do that

**Comment by Haggle1996** [comment]
Some time ago, Vazkii changed the passive flowers (dayblooms, hydroangeas, and nightblooms) so that they wither away and die after a few minecraft days. They are useful only to get some starter mana. Your primary early-botania flower is the endo flame. There are several ways to automate this flower, along with other mana-producing flowers.
